package org.nting.toolkit.component;

import static org.nting.toolkit.ToolkitServices.fontManager;
import static org.nting.toolkit.ui.Colors.GREY;

import org.nting.data.Property;
import org.nting.toolkit.FontManager.FontSize;
import org.nting.toolkit.ui.stone.Content;
import org.nting.toolkit.ui.stone.TextContentSingleLine;

import playn.core.Font;
import playn.core.Platform;
import playn.core.PlayN;
import pythagoras.f.Dimension;

/* @formatter:off
 *
 * http://icomoon.io/
 * https://vaadin.com/font-icons
 * https://www.google.com/design/icons/index.html
 * http://www.entypo.com/
 */
public enum FontIcon implements Icon {

    // Vaadin Icons
    BOOK_DOLLAR, BOOK_PERCENT, BRIEFCASE, PLUS_MINUS, CALENDAR_BRIEFCASE, CALENDAR_CLOCK, CALENDAR_USER, DENTAL_CHAIR,
    DOCTOR_BRIEFCASE, DOCTOR, DOLLAR, EXIT_O, EXIT, GOLF, GROUP, HEALTH_CARD, INVOICE, LEVEL_DOWN_BOLD, LEVEL_LEFT_BOLD,
    LEVEL_UP_BOLD, OUT, PILL, PILLS, SPECIALIST, STETHOSCOPE, TEETH, USER_CARD, USER_CHECK, USER_CLOCK, USER_HEART,
    ABSOLUTE_POSITION, ACCORDION_MENU, ADD_DOCK, ARCHIVES, ARROW_BACKWARD, ARROW_FORWARD, AT, BELL_SLASH_O, BELL_SLASH,
    BOAT, BROWSER, BULLETS, BUTTON, CALC_BOOK, CALENDAR_ENVELOPE, CAR, CHECK_SQUARE, CHILD, CLIPBOARD_CROSS,
    CLIPBOARD_HEART, CLIPBOARD_PULSE, CLIPBOARD_TEXT, CLIPBOARD_USER, CLIPBOARD, COMBOBOX, COMPRESS_SQUARE, COPYRIGHT,
    CSS, CURLY_BRACKETS, DATE_INPUT, ELASTIC, ENVELOPE_OPEN_O, ENVELOPE_OPEN, EXTERNAL_BROWSER, EYEDROPPER, FACTORY,
    FILE_PROCESS, FILE_REFRESH, FILE_START, FILE_TREE_SMALL, FILE_TREE_SUB, FILE_TREE, ADOBE_FLASH, FLIP_H, FLIP_V,
    FORM, FUNCION, GRAB, GRID_BEVEL, GRID_H, GRID_V, GRID, HAND, INPUT, LAYOUT, LEVEL_RIGHT_BOLD, LIST_SELECT,
    MARGIN_BOTTOM, MARGIN_LEFT, MARGIN_RIGHT, MARGIN_TOP, MARGIN, NATIVE_BUTTON, NOTEBOOK, OPTIONS, ORIENTATION, OUTBOX,
    PADDING_BOTTOM, PADDING_LEFT, PADDING_RIGHT, PADDING_TOP, PADDING, PAINT_ROLL, PALETE, PANEL, PASSWORD, PLUG,
    POINTER, PROGRESSBAR, RESIZE_H, RESIZE_V, RHOMBUS, ROAD_BRANCH, ROAD_BRANCHES, ROAD_SPLIT, SELECT, SLIDER, SPLIT,
    START_COG, STOP_COG, SWORD, TABS, TAXI, TEXT_INPUT, TEXT_LABEL, TOOTH, TRAIN, TREE_TABLE, TWIN_COL_SELECT, VIEWPORT,
    ABACUS, ACCESSIBILITY, AIRPLANE, ANCHOR, ASTERISK, AUTOMATION, BARCODE, BOMB, BUG_O, BUG, CALC, CHART_LINE, CHART,
    CODE, COFFEE, COGS, CONTROLLER, CORNER_LOWER_LEFT, CORNER_LOWER_RIGHT, CORNER_UPPER_LEFT, CORNER_UPPER_RIGHT, CUBE,
    CUBES, DOWNLOAD_ALT, ERASER, FACEBOOK_SQUARE, FACEBOOK, FEMALE, FILE_FONT, FILE_PRESENTATION, FILE_TABLE, FILL,
    FILTER, FIRE, FROWN_O, GAVEL, GOOGLE_PLUS_SQUARE, GOOGLE_PLUS, HANDS_UP, HASH, INSTITUTION, KEY_O, KEY, LIFEBUOY,
    LIGHTBULB, SIGN_IN_ALT, SIGN_OUT_ALT, MAGIC, MALE, MEDAL, MEGAFONE, MEH_O, MONEY, PACKAGE, PAINTBRUSH, PAPERPLANE,
    PAPERPLANE2, PARAGRAPH, PASTE, PIE_CHART, PIN_POST, PRESENTATION, PUZZLE_PIECE, QRCODE, QUOTE_LEFT, QUOTE_RIGHT,
    RASTER_LOWER_LEFT, RASTER, RECYCLE, ROAD, ROCKET, RSS_SQUARE, RSS, SAFE_LOCK, SAFE, SHARE_SQUARE, SHIELD, SLIDERS,
    SMILEY_O, SPINNER_ARC, SPINNER_THIRD, SPINNER, SUBSCRIPT, SUPERSCRIPT, TAG, TAGS, TERMINAL, THUMBS_DOWN_O,
    THUMBS_DOWN, THUMBS_UP_O, THUMBS_UP, TRUCK, TWITTER_SQUARE, TWITTER, UMBRELLA, UPLOAD_ALT, VIMEO_SQUARE, VIMEO,
    YOUTUBE_SQUARE, YOUTUBE, ANGLE_DOUBLE_DOWN, ANGLE_DOUBLE_LEFT, ANGLE_DOUBLE_RIGHT, ANGLE_DOUBLE_UP, ANGLE_DOWN,
    ANGLE_LEFT, ANGLE_RIGHT, ANGLE_UP, ARCHIVE, ARROW_CIRCLE_DOWN_O, ARROW_CIRCLE_DOWN, ARROW_CIRCLE_LEFT_O,
    ARROW_CIRCLE_LEFT, ARROW_CIRCLE_RIGHT_O, ARROW_CIRCLE_RIGHT, ARROW_CIRCLE_UP_O, ARROW_CIRCLE_UP, BAN, BOLD, BOOK,
    BULLSEYE, CART_O, CART, CHECK_SQUARE_O, CROSS_CUTLERY, CUTLERY, DASHBOARD, DISC, DOT_CIRCLE, DOWNLOAD, DROP,
    EXCHANGE, EXCLAMATION_CIRCLE_O, EXCLAMATION_CIRCLE, EXCLAMATION, EYE_SLASH, FILE_CODE, FILE_MOVIE, FILE_PICTURE,
    FILE_SOUND, FILE_ZIP, FLAG_CHECKERED, FLAG_O, FLAG, FLASH, FONT, GAMEPAD, GIFT, HANDLE_CORNER, HARDDRIVE_O,
    HARDDRIVE, HEADER, HEADPHONES, INBOX, INFO_CIRCLE_O, INFO_CIRCLE, INFO, LIST_OL, ITALIC, KEYBOARD_O, KEYBOARD,
    LINE_H, LINE_V, LINK, LOCATION_ARROW_CIRCLE_O, LOCATION_ARROW_CIRCLE, LOCATION_ARROW, MAILBOX, MICROPHONE,
    MODAL_LIST, MUTE, PAPERCLIP, PLAY_CIRCLE_O, QUESTION_CIRCLE_O, QUESTION_CIRCLE, PLAY_CIRCLE, QUESTION, RANDOM,
    SCISSORS, SCREWDRIVER, SERVER, DATABASE, SIGNAL, SITEMAP, SPOON, STRIKETHROUGH, SUN_O, TASKS, TEXT_HEIGHT,
    TEXT_WIDTH, TICKET, TOOLBOX, TOOLS, TROPHY, UNDERLINE, UNLINK, UPLOAD, USERS, WARNING, WRENCH, ADJUST, ALIGN_CENTER,
    ALIGN_LEFT, ALIGN_RIGHT, ARROW_LONG_DOWN, ARROW_LONG_LEFT, ARROWS_CROSS, ARROWS_LONG_H, ARROWS_LONG_RIGHT,
    ARROWS_LONG_UP, ARROWS_LONG_V, ARROWS, BACKWARDS, BAR_CHART, BELL_O, BOLT, CHAT, CHECK, CIRCLE_THIN, CIRCLE,
    CLOUD_DOWNLOAD_O, CLOUD_DOWNLOAD, CLOUD_O, CLOUD_UPLOAD_O, CLOUD_UPLOAD, CLOUD, COG_O, COMMENT_ELLIPSIS_O,
    COMMENT_ELLIPSIS, COMMENT_O, COMMENT, COMMENTS_O, COMMENTS, COMPRESS, CONNECT_O, CONNECT, CREDIT_CARD, CROP,
    DEINDENT, EDIT, EJECT, ELLIPSIS_H, ELLIPSIS_V, EXPAND_FULL, EXPAND, FAST_BACKWARD, FAST_FORWARD, FILM,
    FOLDER_OPEN_O, FOLDER_OPEN, FORWARD, GLASS, GLOBE, HEART_O, HEART, INDENT, LAPTOP, LEVEL_DOWN, LEVEL_LEFT,
    LEVEL_RIGHT, LEVEL_UP, MAGNET, MAP_MARKER, MOON_O, MOON, MOVIE, MUSIC, PAUSE, PLAY, POWER_OFF, REFRESH, REPLY_ALL,
    REPLY, RETWEET, ROTATE_LEFT, ROTATE_RIGHT, SHARE, SIGN_IN, SIGN_OUT, SORT, SOUND_DISABLE, SQUARE_SHADOW,
    STAR_HALF_LEFT_O, STAR_HALF_LEFT, STAR_HALF_RIGHT_O, STAR_HALF_RIGHT, STAR_O, STAR, STEP_BACKWARD, STEP_FORWARD,
    STOP, TABLE, THIN_SQUARE, TIME_BACKWARD, TIME_FORWARD, VOLUME_DOWN, VOLUME_OFF, VOLUME_UP, VOLUME, CLOSE,
    ALIGN_JUSTIFY, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, ARROW_UP, MENU, BELL, BOOKMARK_O, BOOKMARK, BUILDING_O,
    BUILDING, CALENDAR_O, CALENDAR, CAMERA, CARET_DOWN, CARET_LEFT, CARET_RIGHT, CARET_SQUARE_DOWN_O,
    CARET_SQUARE_LEFT_O, CARET_SQUARE_RIGHT_O, CARET_SQUARE_UP_O, CARET_UP, CHECK_CIRCLE_O, CHECK_CIRCLE,
    CHEVRON_CIRCLE_DOWN_O, CHEVRON_CIRCLE_DOWN, CHEVRON_CIRCLE_LEFT_O, CHEVRON_CIRCLE_LEFT, CHEVRON_CIRCLE_RIGHT_O,
    CHEVRON_CIRCLE_RIGHT, CHEVRON_CIRCLE_UP_O, CHEVRON_CIRCLE_UP, CHEVRON_DOWN, CHEVRON_LEFT, CHEVRON_RIGHT, CHEVRON_UP,
    CLOCK, COG, COPY_O, COPY, CROSSHAIRS, DESKTOP, INSERT, ELLIPSIS_CIRCLE_O, ELLIPSIS_CIRCLE, ENVELOPE_O, ENVELOPE,
    EXPAND_SQUARE, EXTERNAL_LINK, EYE, FILE_O, FILE_TEXT_O, FILE_TEXT, FILE, FLASK, FOLDER_O, FOLDER, GLASSES,
    GRID_BIG_O, GRID_BIG, GRID_SMALL_O, GRID_SMALL, HOME_O, HOME, LINES_LIST, LINES, LIST_UL, LIST, LOCK,
    MINUS_CIRCLE_O, MINUS_CIRCLE, MINUS_SQUARE_LEFT_O, MINUS, MOBILE, MODAL, OPEN_BOOK, PENCIL, PHONE, PICTURE, PIN,
    PLUS_CIRCLE_O, PLUS_CIRCLE, PLUS_SQUARE_LEFT_O, PLUS, PRINT, SEARCH_MINUS, SEARCH_PLUS, SEARCH, AREA_SELECT,
    SPLIT_H, SPLIT_V, SUITCASE, TABLET, TRASH, UNLOCK, USER, VAADIN_H, VAADIN_V, CLOSE_CIRCLE_O, CLOSE_CIRCLE,
    // Android/Material icons
    ERROR, ERROR_OUTLINE, WARNING3, ADD_ALERT, ALBUM, AV_TIMER, CLOSED_CAPTION, EQUALIZER, EXPLICIT, FAST_FORWARD_M,
    FAST_REWIND, GAMES, HEARING, HIGH_QUALITY, LOOP, MIC, MIC_NONE, MIC_OFF, MOVIE2, LIBRARY_ADD, LIBRARY_BOOKS,
    LIBRARY_MUSIC, NEW_RELEASES, NOT_INTERESTED, PAUSE2, PAUSE_CIRCLE_FILLED, PAUSE_CIRCLE_OUTLINE, PLAY_ARROW,
    PLAY_CIRCLE_FILLED, PLAY_CIRCLE_OUTLINE, PLAYLIST_ADD, QUEUE, QUEUE_MUSIC, RADIO, RECENT_ACTORS, REPEAT, REPEAT_ONE,
    REPLAY, SHUFFLE, SKIP_NEXT, SKIP_PREVIOUS, SNOOZE, STOP2, SUBTITLES, SURROUND_SOUND, VIDEO_COLLECTION, VIDEOCAM,
    VIDEOCAM_OFF, VOLUME_DOWN_M, VOLUME_MUTE, VOLUME_OFF_M, VOLUME_UP_M, WEB, HD, SORT_BY_ALPHA, AIRPLAY, FORWARD_10,
    FORWARD_30, FORWARD_5, REPLAY_10, REPLAY_30, REPLAY_5, BUSINESS, CALL, CALL_END, CALL_MADE, CALL_MERGE, CALL_MISSED,
    CALL_RECEIVED, CALL_SPLIT, CHAT2, CLEAR_ALL, COMMENT2, CONTACTS, DIALER_SIP, DIALPAD, EMAIL, FORUM, IMPORT_EXPORT,
    INVERT_COLORS_OFF, LIVE_HELP, LOCATION_OFF, LOCATION_ON, MESSAGE, CHAT_BUBBLE, CHAT_BUBBLE_OUTLINE, NO_SIM, PHONE2,
    PORTABLE_WIFI_OFF, CONTACT_PHONE, RING_VOLUME, SPEAKER_PHONE, STAY_CURRENT_LANDSCAPE, STAY_CURRENT_PORTRAIT,
    STAY_PRIMARY_LANDSCAPE, STAY_PRIMARY_PORTRAIT, SWAP_CALLS, TEXTSMS, VOICEMAIL, VPN_KEY, PHONELINK_ERASE,
    PHONELINK_LOCK, PHONELINK_RING, PHONELINK_SETUP, PRESENT_TO_ALL, ADD, ADD_BOX, ADD_CIRCLE, ADD_CIRCLE_OUTLINE,
    ARCHIVE2, BACKSPACE, BLOCK, CLEAR, CONTENT_COPY, CONTENT_CUT, CONTENT_PASTE, CREATE, DRAFTS, FILTER_LIST, FLAG2,
    FORWARD2, GESTURE, INBOX2, LINK2, MAIL, MARKUNREAD, REDO, REMOVE, REMOVE_CIRCLE, REMOVE_CIRCLE_OUTLINE, REPLY2,
    REPLY_ALL_M, REPORT, SAVE, SELECT_ALL, SEND, SORT2, TEXT_FORMAT, UNDO, FONT_DOWNLOAD, ACCESS_ALARM, ACCESS_ALARMS,
    ACCESS_TIME, ADD_ALARM, AIRPLANEMODE_INACTIVE, AIRPLANEMODE_ACTIVE, BATTERY_ALERT, BATTERY_CHARGING_FULL,
    BATTERY_FULL, BATTERY_STD, BATTERY_UNKNOWN, BLUETOOTH, BLUETOOTH_CONNECTED, BLUETOOTH_DISABLED, BLUETOOTH_SEARCHING,
    BRIGHTNESS_AUTO, BRIGHTNESS_HIGH, BRIGHTNESS_LOW, BRIGHTNESS_MEDIUM, DATA_USAGE, DEVELOPER_MODE, DEVICES, DVR,
    GPS_FIXED, GPS_NOT_FIXED, GPS_OFF, LOCATION_DISABLED, LOCATION_SEARCHING, GRAPHIC_EQ, NETWORK_CELL, NETWORK_WIFI,
    NFC, NOW_WALLPAPER, NOW_WIDGETS, SCREEN_LOCK_LANDSCAPE, SCREEN_LOCK_PORTRAIT, SCREEN_LOCK_ROTATION, SCREEN_ROTATION,
    SD_STORAGE, SETTINGS_SYSTEM_DAYDREAM, SIGNAL_CELLULAR_4_BAR, SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR,
    SIGNAL_CELLULAR_NO_SIM, SIGNAL_CELLULAR_NULL, SIGNAL_CELLULAR_OFF, SIGNAL_WIFI_4_BAR, SIGNAL_WIFI_4_BAR_LOCK,
    SIGNAL_WIFI_OFF, STORAGE, USB, WIFI_LOCK, WIFI_TETHERING, ATTACH_FILE, ATTACH_MONEY, BORDER_ALL, BORDER_BOTTOM,
    BORDER_CLEAR, BORDER_COLOR, BORDER_HORIZONTAL, BORDER_INNER, BORDER_LEFT, BORDER_OUTER, BORDER_RIGHT, BORDER_STYLE,
    BORDER_TOP, BORDER_VERTICAL, FORMAT_ALIGN_CENTER, FORMAT_ALIGN_JUSTIFY, FORMAT_ALIGN_LEFT, FORMAT_ALIGN_RIGHT,
    FORMAT_BOLD, FORMAT_CLEAR, FORMAT_COLOR_FILL, FORMAT_COLOR_RESET, FORMAT_COLOR_TEXT, FORMAT_INDENT_DECREASE,
    FORMAT_INDENT_INCREASE, FORMAT_ITALIC, FORMAT_LINE_SPACING, FORMAT_LIST_BULLETED, FORMAT_LIST_NUMBERED,
    FORMAT_PAINT, FORMAT_QUOTE, FORMAT_SIZE, FORMAT_STRIKETHROUGH, FORMAT_TEXTDIRECTION_L_TO_R,
    FORMAT_TEXTDIRECTION_R_TO_L, FORMAT_UNDERLINED, FUNCTIONS, INSERT_CHART, INSERT_COMMENT, INSERT_DRIVE_FILE,
    INSERT_EMOTICON, INSERT_INVITATION, INSERT_LINK, INSERT_PHOTO, MERGE_TYPE, MODE_COMMENT, MODE_EDIT, PUBLISH,
    SPACE_BAR, STRIKETHROUGH_S, VERTICAL_ALIGN_BOTTOM, VERTICAL_ALIGN_CENTER, VERTICAL_ALIGN_TOP, WRAP_TEXT, MONEY_OFF,
    ATTACHMENT, CLOUD2, CLOUD_CIRCLE, CLOUD_DONE, CLOUD_DOWNLOAD_M, CLOUD_OFF, CLOUD_QUEUE, CLOUD_UPLOAD_M,
    FILE_DOWNLOAD, FILE_UPLOAD, FOLDER2, FOLDER_OPEN_M, FOLDER_SHARED, CAST, CAST_CONNECTED, COMPUTER, DESKTOP_MAC,
    DESKTOP_WINDOWS, DEVELOPER_BOARD, DOCK, GAMEPAD2, HEADSET, HEADSET_MIC, KEYBOARD2, KEYBOARD_ARROW_DOWN,
    KEYBOARD_ARROW_LEFT, KEYBOARD_ARROW_RIGHT, KEYBOARD_ARROW_UP, KEYBOARD_BACKSPACE, KEYBOARD_CAPSLOCK, KEYBOARD_HIDE,
    KEYBOARD_RETURN, KEYBOARD_TAB, KEYBOARD_VOICE, LAPTOP2, LAPTOP_CHROMEBOOK, LAPTOP_MAC, LAPTOP_WINDOWS, MEMORY,
    MOUSE, PHONE_ANDROID, PHONE_IPHONE, PHONELINK, PHONELINK_OFF, ROUTER, SCANNER, SECURITY, SIM_CARD, SMARTPHONE,
    SPEAKER, SPEAKER_GROUP, TABLET2, TABLET_ANDROID, TABLET_MAC, TOYS, TV, WATCH, DEVICE_HUB, POWER_INPUT,
    ADD_TO_PHOTOS, ADJUST2, ASSISTANT, ASSISTANT_PHOTO, AUDIOTRACK, BLUR_CIRCULAR, BLUR_LINEAR, BLUR_OFF, BLUR_ON,
    BRIGHTNESS_1, BRIGHTNESS_2, BRIGHTNESS_3, BRIGHTNESS_4, BRIGHTNESS_5, BRIGHTNESS_6, BRIGHTNESS_7, BROKEN_IMAGE,
    BRUSH, CAMERA2, CAMERA_ALT, CAMERA_FRONT, CAMERA_REAR, CAMERA_ROLL, CENTER_FOCUS_STRONG, CENTER_FOCUS_WEAK,
    COLLECTIONS, COLOR_LENS, COLORIZE, COMPARE, CONTROL_POINT, CONTROL_POINT_DUPLICATE, CROP_16_9, CROP_3_2, CROP2,
    CROP_5_4, CROP_7_5, CROP_DIN, CROP_FREE, CROP_LANDSCAPE, CROP_ORIGINAL, CROP_PORTRAIT, CROP_SQUARE, DEHAZE, DETAILS,
    EDIT2, EXPOSURE, EXPOSURE_MINUS_1, EXPOSURE_MINUS_2, EXPOSURE_PLUS_1, EXPOSURE_PLUS_2, EXPOSURE_ZERO, FILTER_1,
    FILTER_2, FILTER_3, FILTER2, FILTER_4, FILTER_5, FILTER_6, FILTER_7, FILTER_8, FILTER_9, FILTER_9_PLUS,
    FILTER_B_AND_W, FILTER_CENTER_FOCUS, FILTER_DRAMA, FILTER_FRAMES, FILTER_HDR, FILTER_NONE, FILTER_TILT_SHIFT,
    FILTER_VINTAGE, FLARE, FLASH_AUTO, FLASH_OFF, FLASH_ON, FLIP, GRADIENT, GRAIN, GRID_OFF, GRID_ON, HDR_OFF, HDR_ON,
    HDR_STRONG, HDR_WEAK, HEALING, IMAGE, IMAGE_ASPECT_RATIO, ISO, LANDSCAPE, LEAK_ADD, LEAK_REMOVE, LENS, LOOKS_3,
    LOOKS, LOOKS_4, LOOKS_5, LOOKS_6, LOOKS_ONE, LOOKS_TWO, LOUPE, MONOCHROME_PHOTOS, MOVIE_CREATION, MUSIC_NOTE,
    NATURE, NATURE_PEOPLE, NAVIGATE_BEFORE, NAVIGATE_NEXT, PALETTE, PANORAMA, PANORAMA_FISH_EYE, PANORAMA_HORIZONTAL,
    PANORAMA_VERTICAL, PANORAMA_WIDE_ANGLE, PHOTO, PHOTO_ALBUM, PHOTO_CAMERA, PHOTO_LIBRARY, PICTURE_AS_PDF, PORTRAIT,
    REMOVE_RED_EYE, ROTATE_90_DEGREES_CCW, ROTATE_LEFT_M, ROTATE_RIGHT_M, SLIDESHOW, STRAIGHTEN, STYLE, SWITCH_CAMERA,
    SWITCH_VIDEO, TAG_FACES, TEXTURE, TIMELAPSE, TIMER_10, TIMER_3, TIMER, TIMER_OFF, TONALITY, TRANSFORM, TUNE,
    VIEW_COMFORTABLE, VIEW_COMPACT, WB_AUTO, WB_CLOUDY, WB_INCANDESCENT, WB_SUNNY, COLLECTIONS_BOOKMARK,
    PHOTO_SIZE_SELECT_ACTUAL, PHOTO_SIZE_SELECT_LARGE, PHOTO_SIZE_SELECT_SMALL, VIGNETTE, WB_IRIDESCENT, BEENHERE,
    DIRECTIONS, DIRECTIONS_BIKE, DIRECTIONS_BUS, DIRECTIONS_CAR, DIRECTIONS_FERRY, DIRECTIONS_SUBWAY,
    DIRECTIONS_RAILWAY, DIRECTIONS_TRANSIT, DIRECTIONS_WALK, FLIGHT, HOTEL, LAYERS, LAYERS_CLEAR, LOCAL_AIRPORT,
    LOCAL_ATM, LOCAL_ATTRACTION, LOCAL_BAR, LOCAL_CAFE, LOCAL_CAR_WASH, LOCAL_CONVENIENCE_STORE, LOCAL_DRINK,
    LOCAL_FLORIST, LOCAL_GAS_STATION, LOCAL_GROCERY_STORE, LOCAL_HOSPITAL, LOCAL_HOTEL, LOCAL_LAUNDRY_SERVICE,
    LOCAL_LIBRARY, LOCAL_MALL, LOCAL_MOVIES, LOCAL_OFFER, LOCAL_PARKING, LOCAL_PHARMACY, LOCAL_PHONE, LOCAL_PIZZA,
    LOCAL_PLAY, LOCAL_POST_OFFICE, LOCAL_PRINT_SHOP, LOCAL_RESTAURANT, LOCAL_SEE, LOCAL_SHIPPING, LOCAL_TAXI,
    LOCATION_HISTORY, MAP, MY_LOCATION, NAVIGATION, PIN_DROP, PLACE, RATE_REVIEW, RESTAURANT_MENU, SATELLITE,
    STORE_MALL_DIRECTORY, TERRAIN, TRAFFIC, DIRECTIONS_RUN, APPS, ARROW_BACK, ARROW_DROP_DOWN, ARROW_DROP_DOWN_CIRCLE,
    ARROW_DROP_UP, ARROW_FORWARD_M, CANCEL3, CHECK2, CHEVRON_LEFT_M, CHEVRON_RIGHT_M, CLOSE2, EXPAND_LESS, EXPAND_MORE,
    FULLSCREEN, FULLSCREEN_EXIT, MENU2, KEYBOARD_CONTROL, MORE_VERT, REFRESH2, UNFOLD_LESS, UNFOLD_MORE, ADB,
    BLUETOOTH_AUDIO, DISC_FULL, DO_NOT_DISTURB_ALT, DO_NOT_DISTURB, DRIVE_ETA, EVENT_AVAILABLE, EVENT_BUSY, EVENT_NOTE,
    FOLDER_SPECIAL, MMS, MORE, NETWORK_LOCKED, PHONE_BLUETOOTH_SPEAKER, PHONE_FORWARDED, PHONE_IN_TALK, PHONE_LOCKED,
    PHONE_MISSED, PHONE_PAUSED, SD_CARD, SIM_CARD_ALERT, SMS, SMS_FAILED, SYNC, SYNC_DISABLED, SYNC_PROBLEM,
    SYSTEM_UPDATE, TAP_AND_PLAY, TIME_TO_LEAVE, VIBRATION, VOICE_CHAT, VPN_LOCK, AIRLINE_SEAT_FLAT,
    AIRLINE_SEAT_FLAT_ANGLED, AIRLINE_SEAT_INDIVIDUAL_SUITE, AIRLINE_SEAT_LEGROOM_EXTRA, AIRLINE_SEAT_LEGROOM_NORMAL,
    AIRLINE_SEAT_LEGROOM_REDUCED, AIRLINE_SEAT_RECLINE_EXTRA, AIRLINE_SEAT_RECLINE_NORMAL, CONFIRMATION_NUMBER, LIVE_TV,
    ONDEMAND_VIDEO, PERSONAL_VIDEO, POWER, WC, WIFI, CAKE, DOMAIN, GROUP2, GROUP_ADD, LOCATION_CITY, MOOD, MOOD_BAD,
    NOTIFICATIONS, NOTIFICATIONS_NONE, NOTIFICATIONS_OFF, NOTIFICATIONS_ACTIVE, NOTIFICATIONS_PAUSED, PAGES, PARTY_MODE,
    PEOPLE, PEOPLE_OUTLINE, PERSON, PERSON_ADD, PERSON_OUTLINE, PLUS_ONE, POLL, PUBLIC, SCHOOL, SHARE2, WHATSHOT,
    CHECK_BOX, CHECK_BOX_OUTLINE_BLANK, RADIO_BUTTON_UNCHECKED, RADIO_BUTTON_CHECKED, STAR2, STAR_HALF, STAR_OUTLINE,
    ROTATION_3D, ACCESSIBILITY2, ACCOUNT_BALANCE, ACCOUNT_BALANCE_WALLET, ACCOUNT_BOX, ACCOUNT_CIRCLE,
    ADD_SHOPPING_CART, ALARM, ALARM_ADD, ALARM_OFF, ALARM_ON, ANDROID, ANNOUNCEMENT, ASPECT_RATIO, ASSESSMENT,
    ASSIGNMENT, ASSIGNMENT_IND, ASSIGNMENT_LATE, ASSIGNMENT_RETURN, ASSIGNMENT_RETURNED, ASSIGNMENT_TURNED_IN,
    AUTORENEW, BACKUP, BOOK2, BOOKMARK2, BOOKMARK_OUTLINE, BUG_REPORT, BUILD, CACHED, CHANGE_HISTORY, CHECK_CIRCLE_M,
    CHROME_READER_MODE, CLASS, CODE2, CREDIT_CARD_M, DASHBOARD2, DELETE, DESCRIPTION, DNS, DONE, DONE_ALL, EVENT,
    EXIT_TO_APP, EXPLORE, EXTENSION, FACE, FAVORITE, FAVORITE_OUTLINE, FEEDBACK, FIND_IN_PAGE, FIND_REPLACE,
    FLIP_TO_BACK, FLIP_TO_FRONT, GET_APP, GRADE, GROUP_WORK, HELP, HIGHLIGHT_REMOVE, HISTORY, HOME2, HOURGLASS_EMPTY,
    HOURGLASS_FULL, HTTPS, INFO2, INFO_OUTLINE, INPUT2, INVERT_COLORS_ON, LABEL, LABEL_OUTLINE, LANGUAGE2, LAUNCH,
    LIST2, LOCK2, LOCK_OPEN, LOCK_OUTLINE, LOYALTY, MARKUNREAD_MAILBOX, NOTE_ADD, OPEN_IN_BROWSER, OPEN_IN_NEW,
    OPEN_WITH, PAGEVIEW, PAYMENT, PERM_CAMERA_MIC, PERM_CONTACT_CALENDAR, PERM_DATA_SETTING, PERM_DEVICE_INFORMATION,
    PERM_IDENTITY, PERM_MEDIA, PERM_PHONE_MSG, PERM_SCAN_WIFI, PICTURE_IN_PICTURE, POLYMER, POWER_SETTINGS_NEW, PRINT2,
    QUERY_BUILDER, QUESTION_ANSWER, RECEIPT, REDEEM, REPORT_PROBLEM, RESTORE, ROOM, SCHEDULE, SEARCH2, SETTINGS,
    SETTINGS_APPLICATIONS, SETTINGS_BACKUP_RESTORE, SETTINGS_BLUETOOTH, SETTINGS_CELL, SETTINGS_BRIGHTNESS,
    SETTINGS_ETHERNET, SETTINGS_INPUT_ANTENNA, SETTINGS_INPUT_COMPONENT, SETTINGS_INPUT_COMPOSITE, SETTINGS_INPUT_HDMI,
    SETTINGS_INPUT_SVIDEO, SETTINGS_OVERSCAN, SETTINGS_PHONE, SETTINGS_POWER, SETTINGS_REMOTE, SETTINGS_VOICE, SHOP,
    SHOP_TWO, SHOPPING_BASKET, SHOPPING_CART, SPEAKER_NOTES, SPELLCHECK, STARS, STORE, SUBJECT, SUPERVISOR_ACCOUNT,
    SWAP_HORIZ, SWAP_VERT, SWAP_VERTICAL_CIRCLE, SYSTEM_UPDATE_ALT, TAB, TAB_UNSELECTED, THEATERS, THUMB_DOWN, THUMB_UP,
    THUMBS_UP_DOWN, TOC, TODAY, TOLL, TRACK_CHANGES, TRANSLATE, TRENDING_DOWN, TRENDING_NEUTRAL, TRENDING_UP, TURNED_IN,
    TURNED_IN_NOT, VERIFIED_USER, VIEW_AGENDA, VIEW_ARRAY, VIEW_CAROUSEL, VIEW_COLUMN, VIEW_DAY, VIEW_HEADLINE, VIEW_LIST,
    VIEW_MODULE, VIEW_QUILT, VIEW_STREAM, VIEW_WEEK, VISIBILITY, VISIBILITY_OFF, CARD_GIFTCARD, CARD_MEMBERSHIP,
    CARD_TRAVEL, WORK, YOUTUBE_SEARCHED_FOR, EJECT2, CAMERA_ENHANCE, HELP_OUTLINE, REORDER, ZOOM_IN, ZOOM_OUT, HTTP,
    EVENT_SEAT, FLIGHT_LAND, FLIGHT_TAKEOFF, PLAY_FOR_WORK, GIF, INDETERMINATE_CHECK_BOX, OFFLINE_PIN,
    // Brankic 1979 icons
    CHECKMARK, CHECKMARK2, CANCEL, CANCEL2, PLUS2, PLUS3, MINUS2, MINUS3, NOTICE, NOTICE2, WARNING2, ALERT,
    // Entypo+ icons
    LANGUAGE;
    /* @formatter:on */

    public Content getContent(FontSize fontSize, int color) {
        Font font = fontManager().getIconFont(fontSize);
        return new IconTextContent(font, color, getCharacter());
    }

    @Override
    public Content getContent(FontSize fontSize, Property<Integer> color) {
        Font font = fontManager().getIconFont(fontSize);
        return new IconTextContent(font, color, getCharacter());
    }

    @Override
    public Content getContent(FontSize fontSize) {
        return getContent(fontSize, GREY);
    }

    @Override
    public Content getContent(float size, int color) {
        Font font = fontManager().getIconFont(size);
        return new IconTextContent(font, color, getCharacter());
    }

    @Override
    public Content getContent(float size) {
        return getContent(size, GREY);
    }

    private String getCharacter() {
        int c = 0xe000 + ordinal();
        return Character.toString((char) c);
    }

    private static class IconTextContent extends TextContentSingleLine {

        public IconTextContent(Font font, int color, String text) {
            super(font, color, text);

            setTranslateX(getPadding() + 1);
            if (PlayN.platformType() == Platform.Type.HTML) {
                setTranslateY(-0.0625f * getFont().size() + 2);
            } else {
                setTranslateY(1);
            }
        }

        public IconTextContent(Font font, Property<Integer> color, String text) {
            super(font, color, text);

            setTranslateX(getPadding() + 1);
            if (PlayN.platformType() == Platform.Type.HTML) {
                setTranslateY(-0.0625f * getFont().size() + 2);
            } else {
                setTranslateY(1);
            }
        }

        @Override
        public Dimension getPreferredSize() {
            float size = getFont().size() + 2;
            return new Dimension(size, size);
        }

        private float getPadding() {
            // NOTE: in FF, height calculation is wrong for this font.
            return (getFont().size() - getPreferredWidth()) / 2f;
        }
    }
}
